### ISSUE TITLE
YouTube Live 下载过程中卡住

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami#34]
**Basic Information**
* Node.js version:  v12.10.0.
* Minyami version: 2.2.14
* Minyami Extractor (Chrome Extension) version: 1.1.6

**Describe the bug**

这个bug最近两天碰到两次，都是下载YTB live（播放中时）
就是正常的从插件复制参数+勾选直播，下载到一半就停住（同时播放的网页正常）不再继续下载，报错如下

```
[MINYAMI][INFO] M3U8 file fetched.
TypeError Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at LiveDownloader.downloader.onChunkNaming (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\dist\core\parsers\
youtube.js:6:53)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\dist\core\live.js:147:79
    at Array.forEach (<anonymous>)
    at LiveDownloader.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\dist\core\live.js:145:34)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\dist\core\live.js:5:58)
>
```
这个Error并不是一定都会导致下载停止，有时候下载还能继续：

![image](https://user-images.githubusercontent.com/4130991/64486521-d1e1b900-d1f3-11e9-9cbf-9bd90b33d407.png)

**Comment by fireattack** [comment]
这个Error并不是一定都会导致下载中断，有时候下载还能继续：

![image](https://user-images.githubusercontent.com/4130991/64486498-99da7600-d1f3-11e9-92bf-fdfaf0a9c0b5.png)

**Comment by fireattack** [comment]
开着debug拿正在播放的[这个直播](https://www.youtube.com/watch?v=93ppFQw7NDE)又试了下，发现这次完全没有报错也会自己停住…

```
[MINYAMI][DEBUG] Downloading 655
[MINYAMI][DEBUG] Downloading 653 succeed.
[MINYAMI][INFO] Proccessing 653 finished. (652 / unknown | Avg Speed: 1.68 chunks/s or 8.35x)
[MINYAMI][DEBUG] Downloading https://r2---sn-ogueln76.googlevideo.com/videoplayback/id/93ppFQw7NDE.1/itag/95/source/yt_live_broadc
ast/expire/1567957253/ei/pcx0XauvA5amgAOYzbnQCQ/ip/66.133.76.23/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bita
g%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r2---sn-ogueln76.googlevideo.com/gcr/jp/playlist_type/DVR/hcs/yes/initcwndbps/
7160/mm/44/mn/sn-ogueln76/ms/lva/mv/m/mvi/1/pl/24/shardbypass/yes/smhost/r4---sn-ogueln7d.googlevideo.com/keepalive/yes/mt/1567935
557/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,gcr,playlist_type/sig/ALgxI2wwRQIhAMFPIzGULkbC0
MLSBjtLTTJ9efh3lt-EujsTWFBTEZgcAiBNZWleflS2xMpon4slnP0SYDn5Mxkrdvg8Ezjiuyv28A%3D%3D/lsparams/hls_chunk_host,hcs,initcwndbps,mm,mn,
ms,mv,mvi,pl,shardbypass,smhost/lsig/AHylml4wRQIgJmINtzZygu7ewu6kwaWoOPWUfdj4JsiG-MgtSgDYFysCIQDhi0tUzMvcK24N7Zp6wDTuhnufEIAtqe0OE
YbPOmexhA%3D%3D/playlist/index.m3u8/sq/656/goap/clen%3D80735%3Blmt%3D1567936514493851/govp/clen%3D535261%3Blmt%3D1567936514493851/
dur/5.000/file/seg.ts
[MINYAMI][DEBUG] Downloading 656
[MINYAMI][DEBUG] Downloading 654 succeed.
[MINYAMI][INFO] Proccessing 654 finished. (653 / unknown | Avg Speed: 1.68 chunks/s or 8.34x)
[MINYAMI][DEBUG] Downloading https://r2---sn-ogueln76.googlevideo.com/videoplayback/id/93ppFQw7NDE.1/itag/95/source/yt_live_broadc
ast/expire/1567957253/ei/pcx0XauvA5amgAOYzbnQCQ/ip/66.133.76.23/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bita
g%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r2---sn-ogueln76.googlevideo.com/gcr/jp/playlist_type/DVR/hcs/yes/initcwndbps/
7160/mm/44/mn/sn-ogueln76/ms/lva/mv/m/mvi/1/pl/24/shardbypass/yes/smhost/r4---sn-ogueln7d.googlevideo.com/keepalive/yes/mt/1567935
557/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,gcr,playlist_type/sig/ALgxI2wwRQIhAMFPIzGULkbC0
MLSBjtLTTJ9efh3lt-EujsTWFBTEZgcAiBNZWleflS2xMpon4slnP0SYDn5Mxkrdvg8Ezjiuyv28A%3D%3D/lsparams/hls_chunk_host,hcs,initcwndbps,mm,mn,
ms,mv,mvi,pl,shardbypass,smhost/lsig/AHylml4wRQIgJmINtzZygu7ewu6kwaWoOPWUfdj4JsiG-MgtSgDYFysCIQDhi0tUzMvcK24N7Zp6wDTuhnufEIAtqe0OE
YbPOmexhA%3D%3D/playlist/index.m3u8/sq/657/goap/clen%3D81247%3Blmt%3D1567936519052924/govp/clen%3D565734%3Blmt%3D1567936519052924/
dur/5.000/file/seg.ts
[MINYAMI][DEBUG] Downloading 657
[MINYAMI][DEBUG] Downloading 655 succeed.
[MINYAMI][INFO] Proccessing 655 finished. (654 / unknown | Avg Speed: 1.68 chunks/s or 8.35x)
[MINYAMI][DEBUG] Downloading 656 succeed.
[MINYAMI][INFO] Proccessing 656 finished. (655 / unknown | Avg Speed: 1.68 chunks/s or 8.34x)
[MINYAMI][DEBUG] Downloading 657 succeed.
[MINYAMI][INFO] Proccessing 657 finished. (656 / unknown | Avg Speed: 1.68 chunks/s or 8.36x)
>
```
