### ISSUE TITLE
Nicolive

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami#36]
**Basic Information**
* Node.js version: v8.9.3
* Minyami version: 2.2.15
* Minyami Extractor (Chrome Extension) version: 1.1.6
* Video URL: https://live2.nicovideo.jp/watch/lv321997509

**Describe the bug**

下载疯狂404/403

其实就是 #28 的问题，上述视频不需要会员也能看前1小时（甚至不需要登录nico），但是无法下载，最多成功下载十几个分段就开始报404，再次测试改报403

Log
```
C:\!Others>minyami -d "https://pc05548cad8.dmc.nico/hlsarchive/ht2_nicolive/nicolive-production-pg20307936019018_344f4f32db888489904e7dc5e67188af22da45f5b98847ed47f53ca4c5a0d3f7/4/ts/playlist.m3u8?start_time=-575255823797&ht2_nicolive=anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b.wcv5up_pyatrz_rtk1mgwcgr8d&start=0" --output "FIVE STARS☆ちゃんねる(MC黒 沢ともよ) - 20190923(月) 1930開始 - ニコニコ生放送.ts" --key "20307936019018_anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b_1569352882_d237537d945c8ec226e36851194a48d0826ec1c9"
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][INFO] Site comfirmed: NicoNico.
[MINYAMI][INFO] Enhanced mode for Nico-TS enabled
[MINYAMI][INFO] Start downloading with 5 thread(s).
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Proccessing 15033.ts finished. (1 / 1436 or 0.07% | Avg Speed: 0.33 chunks/s or 1.67x | ETA: 1h 13m 30s)
[MINYAMI][INFO] Proccessing 10033.ts finished. (2 / 1436 or 0.14% | Avg Speed: 0.67 chunks/s or 3.33x | ETA: 41m 27s)
[MINYAMI][INFO] Proccessing 5033.ts finished. (3 / 1436 or 0.21% | Avg Speed: 0.75 chunks/s or 3.75x | ETA: 30m 13s)
[MINYAMI][INFO] Proccessing 20033.ts finished. (4 / 1436 or 0.28% | Avg Speed: 1.00 chunks/s or 5.00x | ETA: 24m 15s)
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Proccessing 0033.ts finished. (5 / 1436 or 0.35% | Avg Speed: 1.00 chunks/s or 5.00x | ETA: 24m 43s)
[MINYAMI][INFO] Proccessing 25033.ts finished. (6 / 1436 or 0.42% | Avg Speed: 1.00 chunks/s or 5.00x | ETA: 24m 5s)
[MINYAMI][INFO] Proccessing 35033.ts finished. (7 / 1436 or 0.49% | Avg Speed: 1.17 chunks/s or 5.83x | ETA: 20m 47s)
[MINYAMI][INFO] Proccessing 30033.ts finished. (8 / 1436 or 0.56% | Avg Speed: 1.14 chunks/s or 5.71x | ETA: 19m 34s)
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Proccessing 50033.ts finished. (9 / 1436 or 0.63% | Avg Speed: 1.13 chunks/s or 5.63x | ETA: 21m 17s)
[MINYAMI][INFO] Proccessing 55033.ts finished. (10 / 1436 or 0.70% | Avg Speed: 1.25 chunks/s or 6.25x | ETA: 19m 26s)
[MINYAMI][INFO] Proccessing 40033.ts finished. (11 / 1436 or 0.77% | Avg Speed: 1.38 chunks/s or 6.88x | ETA: 17m 47s)
[MINYAMI][INFO] Proccessing 45033.ts finished. (12 / 1436 or 0.84% | Avg Speed: 1.50 chunks/s or 7.50x | ETA: 16m 35s)
[MINYAMI][INFO] Chunk group action <ping> finished.
[MINYAMI][INFO] Proccessing 60033.ts finished. (13 / 1436 or 0.91% | Avg Speed: 1.18 chunks/s or 5.91x | ETA: 19m 25s)
[MINYAMI][INFO] Update Token: anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b.ggbost_pyatsw_20wiw7amixwuh
[MINYAMI][INFO] Proccessing 65033.ts finished. (14 / 1436 or 0.97% | Avg Speed: 1.27 chunks/s or 6.36x | ETA: 19m 27s)
[MINYAMI][WARN] Downloading or decrypting 85033.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Proccessing 70033.ts finished. (15 / 1436 or 1.04% | Avg Speed: 1.25 chunks/s or 6.25x | ETA: 18m 36s)
[MINYAMI][INFO] Proccessing 75033.ts finished. (16 / 1436 or 1.11% | Avg Speed: 1.33 chunks/s or 6.67x | ETA: 18m 6s)
[MINYAMI][WARN] Downloading or decrypting 90033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 105033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 100033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 115033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 110033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 95033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Proccessing 80033.ts finished. (17 / 1436 or 1.18% | Avg Speed: 1.31 chunks/s or 6.54x | ETA: 18m 9s)
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 85033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 135033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 120033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 125033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 130033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 100033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 115033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 105033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 110033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 140033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 145033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 155033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 150033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 160033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 165033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 175033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 170033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 190033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 180033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 185033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 195033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 210033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 215033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 200033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 205033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 220033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 230033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 225033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 235033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 240033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 245033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 255033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 250033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 265033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 260033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 275033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 270033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 280033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 290033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 285033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 300033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 295033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 305033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 315033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 310033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 320033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 330033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 325033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 335033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 340033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 345033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 300033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 350033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 355033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Update Token: anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b.4jh9rd_pyatt6_2wa4vfq63d3j0
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 375033.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 370033.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Downloading or decrypting 365033.ts failed. Retry later. [403 Forbidden]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 403
[MINYAMI][WARN] Downloading or decrypting 360033.ts failed. Retry later. [403 Forbidden]
[MINYAMI][WARN] Downloading or decrypting 390033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 385033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 380033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 345033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 340033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 395033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 400033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 380033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 385033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 415033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 390033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 420033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 415033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 425033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 400033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 405033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 410033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][INFO] Chunk group action <ping> failed.
[MINYAMI][INFO] Error: Request failed with status code 404
[MINYAMI][WARN] Downloading or decrypting 440033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 455033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 425033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 435033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 420033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 445033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 430033.ts failed. Retry later. [404 Not Found]
[MINYAMI][WARN] Downloading or decrypting 450033.ts failed. Retry later. [404 Not Found]
[MINYAMI][INFO] Saving task status.
[MINYAMI][INFO] Downloaded: 17; Waiting for download: 1419
[MINYAMI][INFO] Please wait.

C:\!Others>minyami -d "https://pc05548cad8.dmc.nico/hlsarchive/ht2_nicolive/nicolive-production-pg20307936019018_344f4f32db888489904e7dc5e67188af22da45f5b98847ed47f53ca4c5a0d3f7/4/ts/playlist.m3u8?start_time=-575255823797&ht2_nicolive=anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b.wcv5up_pyatrz_rtk1mgwcgr8d&start=0" --output "FIVE STARS☆ちゃんねる(MC黒 沢ともよ) - 20190923(月) 1930開始 - ニコニコ生放送.ts" --key "20307936019018_anonymous-user-7896034b-748e-41a4-b529-1151bcd0c28b_1569352882_d237537d945c8ec226e36851194a48d0826ec1c9"
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][INFO] Try again.
[MINYAMI][WARN] Fail to fetch M3U8 file: [403 Forbidden]
[MINYAMI][WARN] If you are downloading a live stream, this may result in a broken output video.
[MINYAMI][WARN] Max retries exceeded. Abort.
Error: Max retries exceeded.
    at Object.<anonymous> (C:\Users\ikena\AppData\Roaming\npm\node_modules\minyami\dist\utils\m3u8.js:44:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\ikena\AppData\Roaming\npm\node_modules\minyami\dist\utils\m3u8.js:6:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[MINYAMI][ERROR] Aborted due to critical error.

```

**Comment by Last-Order** [comment]
你有 NicoNico Premium 会员吗

**Comment by fireattack** [comment]
没有囧 所以找了个免费的视频测试

不过我后来换了个环境又下了次，反而成功了

我感觉问题出在浏览器extension段：

我第一次（或者说在环境1上）获取的时候总是能获取到N个m3u8，我随便选了个码率最高（3M？）的就失败了

后来成功那次，只获取到了一个2M的流，就能下载成功

我再观察下，如果只是个例就不麻烦开发者研究了

**Comment by Last-Order** [comment]
对的，你一定得手动选择最高画质再下载。https://www.bilibili.com/read/cv3340753
请看一下faq里面对应的部分。
