### ISSUE TITLE
某些带key的m3u8无法下载 (403)

### ISSUE THREAD

**Issue by fireattack** [Last-Order/Minyami#46]
**Basic Information**
* Node.js version: v12.18.3
* Minyami version: 3.0.9

**Describe the bug**

`http://eqe003odff.eq.webcdn.stream.ne.jp/www50/eqe003odff/jmc_pub/jmc_pd/00011/391907c69ce1460ea991af4865c52ff9_crypt/391907c69ce1460ea991af4865c52ff9_23_cryptmedia.m3u8?__token=EGJqlO+aemAO/q++ed+xonZo3hgyRc7HyGaF0A2Y4KBDGIloj6TGVCN5wwQEjM9H22IL2+9dWh+P2rz7izJ+MNS2dykqQLS2pKljmBg1M0Q=oxDzYycOY20qgypH`

这个地址我用`ffmpeg`和`mpv`都可以正常下载/播放，但是minyami会报403错误

```
[MINYAMI][INFO] Start fetching M3U8 file.
[MINYAMI][INFO] M3U8 file fetched.
[MINYAMI][WARN] Site is not supported by Minyami Core. Try common parser.
undefined
[MINYAMI][INFO] Downloading decrypt keys. (1 / 1)
{ responseType: 'arraybuffer' }
Error Request failed with status code 403 Error: Request failed with status code 403
    at createError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Administrator\AppData\Roaming\npm\node_modules\minyami\node_modules\axios\lib\adapters\http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Last-Order** [comment]
Should be fixed in 3.0.10. Thanks for reporting this problem.
