### ISSUE TITLE
录制m3u8时出现 TypeError Cannot read property '1' of null

### ISSUE THREAD

**Issue by canzz** [Last-Order/Minyami#64]
录制m3u8时出现

TypeError Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at M3U8.getChunkLength (/usr/local/lib/node_modules/minyami/dist/core/m3u8.js:139:72)
    at LiveDownloader.<anonymous> (/usr/local/lib/node_modules/minyami/dist/core/live.js:199:63)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/minyami/dist/core/live.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

之后会一直 Sleep 或者卡在报错后的一个块一直输出这段，而且无法正常中止不能自动合并 只能两次Control+C停掉，无限Sleep后 可以正常中止且自动合并
[MINYAMI][DEBUG] Downloading https://icraft.hs.llnwd.net/ic-www/iphone3/HLS_Layer1/4304_Period3/segment5112.ts
[MINYAMI][DEBUG] Downloading segment5112.ts
[MINYAMI][DEBUG] Downloading segment5112.ts succeed.
[MINYAMI][WARN] Processing segment5112.ts failed.
[MINYAMI][DEBUG] Cannot read property '1' of null

运行
minyami --d "https://www.uniqueradio.jp/agplayerf/hls/HLS_Layer1-cdn.m3u8" --o "output.ts" --live --debug

发生时间不确定，刚开始、开始没多久或者几个小时后 都发生过

win和linux两个环境下都会出现
minyami 3.1.11
nodejs v10.19.0
nodejs v14.15.1

**Comment by Last-Order** [comment]
3.1.12 忽略掉了这个错误，再试试？

**Comment by canzz** [comment]
> 3.1.12 忽略掉了这个错误，再试试？

升到最新版 长时间录了5、6个小时没有发现什么错误 一切正常，应该是没问题了
